### PR TITLE
zig zag traversal of a tree

### PR DESCRIPTION
**Pull request by 2Anshika6**
Added zig zag traversal of a tree

### CODE REVIEW

**Comment by Idhant-6** [comment]
Hi, can you please provide some information on what's the use of this project?

**Comment by 2Anshika6** [comment]
Hello ,
The project is to print ZigZag order traversal of a binary tree. For the
below binary tree the zigzag order traversal will be *1 3 2 7 6 5 4.*

**Comment by Idhant-6** [comment]
That's a nice project! 👍🏻

**Comment by Idhant-6** [comment]
And Don't forget to 🌟 this Repository if you liked it 🙂

**Pull request merged**
