### PR TITLE
Online University Management System

### PR DESCRIPTION
**Pull request by Swayms-stack**
The online University Management System Project In Java is a completely useful Java project which incorporates data about schools, colleges, and schools overall. It was made for the college and its partnered establishments to lead, screen, and dissect confounded exercises like brought together affirmation, unified assessments, and considerably more.

### CODE REVIEW

**Comment by InvisiblePro** [comment]
@Swayms-stack can you explain how it works exactly?
which file to run?

**Comment by InvisiblePro** [comment]
and can you share me this file for checking in my system?
i want to run it

**Comment by Swayms-stack** [comment]
Hello  !
I learnt from this video (https://www.youtube.com/watch?v=0EZjHchCiz0) & I
created one for my college. There are some system requirements.
Kindly go through this page (
https://itsourcecode.com/free-projects/java-projects/university-management-system-project-in-java-with-source-code/
).

**Comment by Idhant-6** [comment]
Great job!! Nice Project!! Keep it up!! 👍🏻

**Comment by Swayms-stack** [comment]
Thank you!

**Pull request merged**
